
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const LoginModal: typeof import("../components/LoginModal.vue")['default']
export const ModelCard: typeof import("../components/ModelCard.vue")['default']
export const ModelCarousel: typeof import("../components/ModelCarousel.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VanActionBar: typeof import("../node_modules/vant/es/action-bar/ActionBar")['default']
export const VanActionBarIcon: typeof import("../node_modules/vant/es/action-bar-icon/ActionBarIcon")['default']
export const VanActionBarButton: typeof import("../node_modules/vant/es/action-bar-button/ActionBarButton")['default']
export const VanActionSheet: typeof import("../node_modules/vant/es/action-sheet/ActionSheet")['default']
export const VanBadge: typeof import("../node_modules/vant/es/badge/Badge")['default']
export const VanAddressList: typeof import("../node_modules/vant/es/address-list/AddressList")['default']
export const VanBackTop: typeof import("../node_modules/vant/es/back-top/BackTop")['default']
export const VanButton: typeof import("../node_modules/vant/es/button/Button")['default']
export const VanAddressEdit: typeof import("../node_modules/vant/es/address-edit/AddressEdit")['default']
export const VanBarrage: typeof import("../node_modules/vant/es/barrage/Barrage")['default']
export const VanCard: typeof import("../node_modules/vant/es/card/Card")['default']
export const VanCalendar: typeof import("../node_modules/vant/es/calendar/Calendar")['default']
export const VanCascader: typeof import("../node_modules/vant/es/cascader/Cascader")['default']
export const VanCell: typeof import("../node_modules/vant/es/cell/Cell")['default']
export const VanCellGroup: typeof import("../node_modules/vant/es/cell-group/CellGroup")['default']
export const VanArea: typeof import("../node_modules/vant/es/area/Area")['default']
export const VanCheckbox: typeof import("../node_modules/vant/es/checkbox/Checkbox")['default']
export const VanCheckboxGroup: typeof import("../node_modules/vant/es/checkbox-group/CheckboxGroup")['default']
export const VanCol: typeof import("../node_modules/vant/es/col/Col")['default']
export const VanCollapse: typeof import("../node_modules/vant/es/collapse/Collapse")['default']
export const VanCollapseItem: typeof import("../node_modules/vant/es/collapse-item/CollapseItem")['default']
export const VanConfigProvider: typeof import("../node_modules/vant/es/config-provider/ConfigProvider")['default']
export const VanCircle: typeof import("../node_modules/vant/es/circle/Circle")['default']
export const VanContactCard: typeof import("../node_modules/vant/es/contact-card/ContactCard")['default']
export const VanCountDown: typeof import("../node_modules/vant/es/count-down/CountDown")['default']
export const VanContactList: typeof import("../node_modules/vant/es/contact-list/ContactList")['default']
export const VanCouponList: typeof import("../node_modules/vant/es/coupon-list/CouponList")['default']
export const VanCouponCell: typeof import("../node_modules/vant/es/coupon-cell/CouponCell")['default']
export const VanDatePicker: typeof import("../node_modules/vant/es/date-picker/DatePicker")['default']
export const VanContactEdit: typeof import("../node_modules/vant/es/contact-edit/ContactEdit")['default']
export const VanDialog: typeof import("../node_modules/vant/es/dialog/Dialog")['default']
export const VanDropdownItem: typeof import("../node_modules/vant/es/dropdown-item/DropdownItem")['default']
export const VanCoupon: typeof import("../node_modules/vant/es/coupon/Coupon")['default']
export const VanField: typeof import("../node_modules/vant/es/field/Field")['default']
export const VanDivider: typeof import("../node_modules/vant/es/divider/Divider")['default']
export const VanDropdownMenu: typeof import("../node_modules/vant/es/dropdown-menu/DropdownMenu")['default']
export const VanEmpty: typeof import("../node_modules/vant/es/empty/Empty")['default']
export const VanFloatingBubble: typeof import("../node_modules/vant/es/floating-bubble/FloatingBubble")['default']
export const VanFloatingPanel: typeof import("../node_modules/vant/es/floating-panel/FloatingPanel")['default']
export const VanForm: typeof import("../node_modules/vant/es/form/Form")['default']
export const VanGrid: typeof import("../node_modules/vant/es/grid/Grid")['default']
export const VanGridItem: typeof import("../node_modules/vant/es/grid-item/GridItem")['default']
export const VanHighlight: typeof import("../node_modules/vant/es/highlight/Highlight")['default']
export const VanIcon: typeof import("../node_modules/vant/es/icon/Icon")['default']
export const VanImagePreview: typeof import("../node_modules/vant/es/image-preview/ImagePreview")['default']
export const VanImage: typeof import("../node_modules/vant/es/image/Image")['default']
export const VanIndexAnchor: typeof import("../node_modules/vant/es/index-anchor/IndexAnchor")['default']
export const VanLoading: typeof import("../node_modules/vant/es/loading/Loading")['default']
export const VanList: typeof import("../node_modules/vant/es/list/List")['default']
export const VanNavBar: typeof import("../node_modules/vant/es/nav-bar/NavBar")['default']
export const VanIndexBar: typeof import("../node_modules/vant/es/index-bar/IndexBar")['default']
export const VanNoticeBar: typeof import("../node_modules/vant/es/notice-bar/NoticeBar")['default']
export const VanNumberKeyboard: typeof import("../node_modules/vant/es/number-keyboard/NumberKeyboard")['default']
export const VanOverlay: typeof import("../node_modules/vant/es/overlay/Overlay")['default']
export const VanPicker: typeof import("../node_modules/vant/es/picker/Picker")['default']
export const VanPagination: typeof import("../node_modules/vant/es/pagination/Pagination")['default']
export const VanPasswordInput: typeof import("../node_modules/vant/es/password-input/PasswordInput")['default']
export const VanNotify: typeof import("../node_modules/vant/es/notify/Notify")['default']
export const VanPickerGroup: typeof import("../node_modules/vant/es/picker-group/PickerGroup")['default']
export const VanPopover: typeof import("../node_modules/vant/es/popover/Popover")['default']
export const VanProgress: typeof import("../node_modules/vant/es/progress/Progress")['default']
export const VanPopup: typeof import("../node_modules/vant/es/popup/Popup")['default']
export const VanPullRefresh: typeof import("../node_modules/vant/es/pull-refresh/PullRefresh")['default']
export const VanRadio: typeof import("../node_modules/vant/es/radio/Radio")['default']
export const VanRadioGroup: typeof import("../node_modules/vant/es/radio-group/RadioGroup")['default']
export const VanRollingText: typeof import("../node_modules/vant/es/rolling-text/RollingText")['default']
export const VanRate: typeof import("../node_modules/vant/es/rate/Rate")['default']
export const VanRow: typeof import("../node_modules/vant/es/row/Row")['default']
export const VanShareSheet: typeof import("../node_modules/vant/es/share-sheet/ShareSheet")['default']
export const VanSidebar: typeof import("../node_modules/vant/es/sidebar/Sidebar")['default']
export const VanSidebarItem: typeof import("../node_modules/vant/es/sidebar-item/SidebarItem")['default']
export const VanSearch: typeof import("../node_modules/vant/es/search/Search")['default']
export const VanSkeletonAvatar: typeof import("../node_modules/vant/es/skeleton-avatar/SkeletonAvatar")['default']
export const VanSkeletonImage: typeof import("../node_modules/vant/es/skeleton-image/SkeletonImage")['default']
export const VanSignature: typeof import("../node_modules/vant/es/signature/Signature")['default']
export const VanSkeletonTitle: typeof import("../node_modules/vant/es/skeleton-title/SkeletonTitle")['default']
export const VanSkeletonParagraph: typeof import("../node_modules/vant/es/skeleton-paragraph/SkeletonParagraph")['default']
export const VanSlider: typeof import("../node_modules/vant/es/slider/Slider")['default']
export const VanSpace: typeof import("../node_modules/vant/es/space/Space")['default']
export const VanSteps: typeof import("../node_modules/vant/es/steps/Steps")['default']
export const VanStep: typeof import("../node_modules/vant/es/step/Step")['default']
export const VanSkeleton: typeof import("../node_modules/vant/es/skeleton/Skeleton")['default']
export const VanSubmitBar: typeof import("../node_modules/vant/es/submit-bar/SubmitBar")['default']
export const VanSticky: typeof import("../node_modules/vant/es/sticky/Sticky")['default']
export const VanSwitch: typeof import("../node_modules/vant/es/switch/Switch")['default']
export const VanStepper: typeof import("../node_modules/vant/es/stepper/Stepper")['default']
export const VanSwipeCell: typeof import("../node_modules/vant/es/swipe-cell/SwipeCell")['default']
export const VanTab: typeof import("../node_modules/vant/es/tab/Tab")['default']
export const VanSwipe: typeof import("../node_modules/vant/es/swipe/Swipe")['default']
export const VanSwipeItem: typeof import("../node_modules/vant/es/swipe-item/SwipeItem")['default']
export const VanTag: typeof import("../node_modules/vant/es/tag/Tag")['default']
export const VanTabbarItem: typeof import("../node_modules/vant/es/tabbar-item/TabbarItem")['default']
export const VanTabs: typeof import("../node_modules/vant/es/tabs/Tabs")['default']
export const VanTextEllipsis: typeof import("../node_modules/vant/es/text-ellipsis/TextEllipsis")['default']
export const VanTabbar: typeof import("../node_modules/vant/es/tabbar/Tabbar")['default']
export const VanTimePicker: typeof import("../node_modules/vant/es/time-picker/TimePicker")['default']
export const VanToast: typeof import("../node_modules/vant/es/toast/Toast")['default']
export const VanWatermark: typeof import("../node_modules/vant/es/watermark/Watermark")['default']
export const VanTreeSelect: typeof import("../node_modules/vant/es/tree-select/TreeSelect")['default']
export const VanUploader: typeof import("../node_modules/vant/es/uploader/Uploader")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyLoginModal: LazyComponent<typeof import("../components/LoginModal.vue")['default']>
export const LazyModelCard: LazyComponent<typeof import("../components/ModelCard.vue")['default']>
export const LazyModelCarousel: LazyComponent<typeof import("../components/ModelCarousel.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyVanActionBar: LazyComponent<typeof import("../node_modules/vant/es/action-bar/ActionBar")['default']>
export const LazyVanActionBarIcon: LazyComponent<typeof import("../node_modules/vant/es/action-bar-icon/ActionBarIcon")['default']>
export const LazyVanActionBarButton: LazyComponent<typeof import("../node_modules/vant/es/action-bar-button/ActionBarButton")['default']>
export const LazyVanActionSheet: LazyComponent<typeof import("../node_modules/vant/es/action-sheet/ActionSheet")['default']>
export const LazyVanBadge: LazyComponent<typeof import("../node_modules/vant/es/badge/Badge")['default']>
export const LazyVanAddressList: LazyComponent<typeof import("../node_modules/vant/es/address-list/AddressList")['default']>
export const LazyVanBackTop: LazyComponent<typeof import("../node_modules/vant/es/back-top/BackTop")['default']>
export const LazyVanButton: LazyComponent<typeof import("../node_modules/vant/es/button/Button")['default']>
export const LazyVanAddressEdit: LazyComponent<typeof import("../node_modules/vant/es/address-edit/AddressEdit")['default']>
export const LazyVanBarrage: LazyComponent<typeof import("../node_modules/vant/es/barrage/Barrage")['default']>
export const LazyVanCard: LazyComponent<typeof import("../node_modules/vant/es/card/Card")['default']>
export const LazyVanCalendar: LazyComponent<typeof import("../node_modules/vant/es/calendar/Calendar")['default']>
export const LazyVanCascader: LazyComponent<typeof import("../node_modules/vant/es/cascader/Cascader")['default']>
export const LazyVanCell: LazyComponent<typeof import("../node_modules/vant/es/cell/Cell")['default']>
export const LazyVanCellGroup: LazyComponent<typeof import("../node_modules/vant/es/cell-group/CellGroup")['default']>
export const LazyVanArea: LazyComponent<typeof import("../node_modules/vant/es/area/Area")['default']>
export const LazyVanCheckbox: LazyComponent<typeof import("../node_modules/vant/es/checkbox/Checkbox")['default']>
export const LazyVanCheckboxGroup: LazyComponent<typeof import("../node_modules/vant/es/checkbox-group/CheckboxGroup")['default']>
export const LazyVanCol: LazyComponent<typeof import("../node_modules/vant/es/col/Col")['default']>
export const LazyVanCollapse: LazyComponent<typeof import("../node_modules/vant/es/collapse/Collapse")['default']>
export const LazyVanCollapseItem: LazyComponent<typeof import("../node_modules/vant/es/collapse-item/CollapseItem")['default']>
export const LazyVanConfigProvider: LazyComponent<typeof import("../node_modules/vant/es/config-provider/ConfigProvider")['default']>
export const LazyVanCircle: LazyComponent<typeof import("../node_modules/vant/es/circle/Circle")['default']>
export const LazyVanContactCard: LazyComponent<typeof import("../node_modules/vant/es/contact-card/ContactCard")['default']>
export const LazyVanCountDown: LazyComponent<typeof import("../node_modules/vant/es/count-down/CountDown")['default']>
export const LazyVanContactList: LazyComponent<typeof import("../node_modules/vant/es/contact-list/ContactList")['default']>
export const LazyVanCouponList: LazyComponent<typeof import("../node_modules/vant/es/coupon-list/CouponList")['default']>
export const LazyVanCouponCell: LazyComponent<typeof import("../node_modules/vant/es/coupon-cell/CouponCell")['default']>
export const LazyVanDatePicker: LazyComponent<typeof import("../node_modules/vant/es/date-picker/DatePicker")['default']>
export const LazyVanContactEdit: LazyComponent<typeof import("../node_modules/vant/es/contact-edit/ContactEdit")['default']>
export const LazyVanDialog: LazyComponent<typeof import("../node_modules/vant/es/dialog/Dialog")['default']>
export const LazyVanDropdownItem: LazyComponent<typeof import("../node_modules/vant/es/dropdown-item/DropdownItem")['default']>
export const LazyVanCoupon: LazyComponent<typeof import("../node_modules/vant/es/coupon/Coupon")['default']>
export const LazyVanField: LazyComponent<typeof import("../node_modules/vant/es/field/Field")['default']>
export const LazyVanDivider: LazyComponent<typeof import("../node_modules/vant/es/divider/Divider")['default']>
export const LazyVanDropdownMenu: LazyComponent<typeof import("../node_modules/vant/es/dropdown-menu/DropdownMenu")['default']>
export const LazyVanEmpty: LazyComponent<typeof import("../node_modules/vant/es/empty/Empty")['default']>
export const LazyVanFloatingBubble: LazyComponent<typeof import("../node_modules/vant/es/floating-bubble/FloatingBubble")['default']>
export const LazyVanFloatingPanel: LazyComponent<typeof import("../node_modules/vant/es/floating-panel/FloatingPanel")['default']>
export const LazyVanForm: LazyComponent<typeof import("../node_modules/vant/es/form/Form")['default']>
export const LazyVanGrid: LazyComponent<typeof import("../node_modules/vant/es/grid/Grid")['default']>
export const LazyVanGridItem: LazyComponent<typeof import("../node_modules/vant/es/grid-item/GridItem")['default']>
export const LazyVanHighlight: LazyComponent<typeof import("../node_modules/vant/es/highlight/Highlight")['default']>
export const LazyVanIcon: LazyComponent<typeof import("../node_modules/vant/es/icon/Icon")['default']>
export const LazyVanImagePreview: LazyComponent<typeof import("../node_modules/vant/es/image-preview/ImagePreview")['default']>
export const LazyVanImage: LazyComponent<typeof import("../node_modules/vant/es/image/Image")['default']>
export const LazyVanIndexAnchor: LazyComponent<typeof import("../node_modules/vant/es/index-anchor/IndexAnchor")['default']>
export const LazyVanLoading: LazyComponent<typeof import("../node_modules/vant/es/loading/Loading")['default']>
export const LazyVanList: LazyComponent<typeof import("../node_modules/vant/es/list/List")['default']>
export const LazyVanNavBar: LazyComponent<typeof import("../node_modules/vant/es/nav-bar/NavBar")['default']>
export const LazyVanIndexBar: LazyComponent<typeof import("../node_modules/vant/es/index-bar/IndexBar")['default']>
export const LazyVanNoticeBar: LazyComponent<typeof import("../node_modules/vant/es/notice-bar/NoticeBar")['default']>
export const LazyVanNumberKeyboard: LazyComponent<typeof import("../node_modules/vant/es/number-keyboard/NumberKeyboard")['default']>
export const LazyVanOverlay: LazyComponent<typeof import("../node_modules/vant/es/overlay/Overlay")['default']>
export const LazyVanPicker: LazyComponent<typeof import("../node_modules/vant/es/picker/Picker")['default']>
export const LazyVanPagination: LazyComponent<typeof import("../node_modules/vant/es/pagination/Pagination")['default']>
export const LazyVanPasswordInput: LazyComponent<typeof import("../node_modules/vant/es/password-input/PasswordInput")['default']>
export const LazyVanNotify: LazyComponent<typeof import("../node_modules/vant/es/notify/Notify")['default']>
export const LazyVanPickerGroup: LazyComponent<typeof import("../node_modules/vant/es/picker-group/PickerGroup")['default']>
export const LazyVanPopover: LazyComponent<typeof import("../node_modules/vant/es/popover/Popover")['default']>
export const LazyVanProgress: LazyComponent<typeof import("../node_modules/vant/es/progress/Progress")['default']>
export const LazyVanPopup: LazyComponent<typeof import("../node_modules/vant/es/popup/Popup")['default']>
export const LazyVanPullRefresh: LazyComponent<typeof import("../node_modules/vant/es/pull-refresh/PullRefresh")['default']>
export const LazyVanRadio: LazyComponent<typeof import("../node_modules/vant/es/radio/Radio")['default']>
export const LazyVanRadioGroup: LazyComponent<typeof import("../node_modules/vant/es/radio-group/RadioGroup")['default']>
export const LazyVanRollingText: LazyComponent<typeof import("../node_modules/vant/es/rolling-text/RollingText")['default']>
export const LazyVanRate: LazyComponent<typeof import("../node_modules/vant/es/rate/Rate")['default']>
export const LazyVanRow: LazyComponent<typeof import("../node_modules/vant/es/row/Row")['default']>
export const LazyVanShareSheet: LazyComponent<typeof import("../node_modules/vant/es/share-sheet/ShareSheet")['default']>
export const LazyVanSidebar: LazyComponent<typeof import("../node_modules/vant/es/sidebar/Sidebar")['default']>
export const LazyVanSidebarItem: LazyComponent<typeof import("../node_modules/vant/es/sidebar-item/SidebarItem")['default']>
export const LazyVanSearch: LazyComponent<typeof import("../node_modules/vant/es/search/Search")['default']>
export const LazyVanSkeletonAvatar: LazyComponent<typeof import("../node_modules/vant/es/skeleton-avatar/SkeletonAvatar")['default']>
export const LazyVanSkeletonImage: LazyComponent<typeof import("../node_modules/vant/es/skeleton-image/SkeletonImage")['default']>
export const LazyVanSignature: LazyComponent<typeof import("../node_modules/vant/es/signature/Signature")['default']>
export const LazyVanSkeletonTitle: LazyComponent<typeof import("../node_modules/vant/es/skeleton-title/SkeletonTitle")['default']>
export const LazyVanSkeletonParagraph: LazyComponent<typeof import("../node_modules/vant/es/skeleton-paragraph/SkeletonParagraph")['default']>
export const LazyVanSlider: LazyComponent<typeof import("../node_modules/vant/es/slider/Slider")['default']>
export const LazyVanSpace: LazyComponent<typeof import("../node_modules/vant/es/space/Space")['default']>
export const LazyVanSteps: LazyComponent<typeof import("../node_modules/vant/es/steps/Steps")['default']>
export const LazyVanStep: LazyComponent<typeof import("../node_modules/vant/es/step/Step")['default']>
export const LazyVanSkeleton: LazyComponent<typeof import("../node_modules/vant/es/skeleton/Skeleton")['default']>
export const LazyVanSubmitBar: LazyComponent<typeof import("../node_modules/vant/es/submit-bar/SubmitBar")['default']>
export const LazyVanSticky: LazyComponent<typeof import("../node_modules/vant/es/sticky/Sticky")['default']>
export const LazyVanSwitch: LazyComponent<typeof import("../node_modules/vant/es/switch/Switch")['default']>
export const LazyVanStepper: LazyComponent<typeof import("../node_modules/vant/es/stepper/Stepper")['default']>
export const LazyVanSwipeCell: LazyComponent<typeof import("../node_modules/vant/es/swipe-cell/SwipeCell")['default']>
export const LazyVanTab: LazyComponent<typeof import("../node_modules/vant/es/tab/Tab")['default']>
export const LazyVanSwipe: LazyComponent<typeof import("../node_modules/vant/es/swipe/Swipe")['default']>
export const LazyVanSwipeItem: LazyComponent<typeof import("../node_modules/vant/es/swipe-item/SwipeItem")['default']>
export const LazyVanTag: LazyComponent<typeof import("../node_modules/vant/es/tag/Tag")['default']>
export const LazyVanTabbarItem: LazyComponent<typeof import("../node_modules/vant/es/tabbar-item/TabbarItem")['default']>
export const LazyVanTabs: LazyComponent<typeof import("../node_modules/vant/es/tabs/Tabs")['default']>
export const LazyVanTextEllipsis: LazyComponent<typeof import("../node_modules/vant/es/text-ellipsis/TextEllipsis")['default']>
export const LazyVanTabbar: LazyComponent<typeof import("../node_modules/vant/es/tabbar/Tabbar")['default']>
export const LazyVanTimePicker: LazyComponent<typeof import("../node_modules/vant/es/time-picker/TimePicker")['default']>
export const LazyVanToast: LazyComponent<typeof import("../node_modules/vant/es/toast/Toast")['default']>
export const LazyVanWatermark: LazyComponent<typeof import("../node_modules/vant/es/watermark/Watermark")['default']>
export const LazyVanTreeSelect: LazyComponent<typeof import("../node_modules/vant/es/tree-select/TreeSelect")['default']>
export const LazyVanUploader: LazyComponent<typeof import("../node_modules/vant/es/uploader/Uploader")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
